-- MySQL Script generated by MySQL Workbench
-- Fri Oct 16 19:47:11 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema my_retail_oltp_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema my_retail_oltp_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `my_retail_oltp_db` DEFAULT CHARACTER SET utf8 ;
USE `my_retail_oltp_db` ;

-- -----------------------------------------------------
-- Table `my_retail_oltp_db`.`Store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_retail_oltp_db`.`Store` (
  `Store id` INT NOT NULL,
  `Store name` VARCHAR(45) NOT NULL,
  `Operation Status` BINARY(10) NOT NULL,
  `Phone Number` VARCHAR(10) NOT NULL,
  `Address` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  PRIMARY KEY (`Store id`),
  UNIQUE INDEX `Employee id_UNIQUE` (`Store id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `my_retail_oltp_db`.`Department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_retail_oltp_db`.`Department` (
  `Department id` INT NOT NULL,
  `Department name` VARCHAR(45) NOT NULL,
  `Store id` INT NOT NULL,
  `Phone Number` VARCHAR(10) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Department id`),
  UNIQUE INDEX `Department id_UNIQUE` (`Department id` ASC) VISIBLE,
  INDEX `fk_Department_Store1_idx` (`Store id` ASC) VISIBLE,
  CONSTRAINT `fk_Department_Store1`
    FOREIGN KEY (`Store id`)
    REFERENCES `my_retail_oltp_db`.`Store` (`Store id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `my_retail_oltp_db`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_retail_oltp_db`.`Employee` (
  `Employee id` INT NOT NULL,
  `First Name` VARCHAR(45) NOT NULL,
  `Last Name` VARCHAR(45) NOT NULL,
  `Department id` INT NOT NULL,
  `Salary` DECIMAL(2) NULL,
  `Phone Number` VARCHAR(10) NOT NULL,
  `Address` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Position` VARCHAR(45) NULL,
  UNIQUE INDEX `Employee id_UNIQUE` (`Employee id` ASC) VISIBLE,
  PRIMARY KEY (`Employee id`),
  INDEX `fk_Employee_Department_idx` (`Department id` ASC) VISIBLE,
  CONSTRAINT `fk_Employee_Department`
    FOREIGN KEY (`Department id`)
    REFERENCES `my_retail_oltp_db`.`Department` (`Department id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `my_retail_oltp_db`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_retail_oltp_db`.`Product` (
  `Product id` INT NOT NULL,
  `Product Name` VARCHAR(45) NULL,
  `Description` VARCHAR(45) NULL,
  `Price` VARCHAR(45) NULL,
  `Category` VARCHAR(45) NULL,
  UNIQUE INDEX `Product id_UNIQUE` (`Product id` ASC) VISIBLE,
  PRIMARY KEY (`Product id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `my_retail_oltp_db`.`Inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_retail_oltp_db`.`Inventory` (
  `Inventory id` INT NOT NULL,
  `Inventory Name` VARCHAR(45) NULL,
  `Store id` INT NULL,
  `Quantity` INT NULL,
  `Product id` INT NOT NULL,
  PRIMARY KEY (`Inventory id`),
  INDEX `fk_Inventory_Store1_idx` (`Store id` ASC) VISIBLE,
  INDEX `fk_Inventory_Product1_idx` (`Product id` ASC) VISIBLE,
  CONSTRAINT `fk_Inventory_Store1`
    FOREIGN KEY (`Store id`)
    REFERENCES `my_retail_oltp_db`.`Store` (`Store id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inventory_Product1`
    FOREIGN KEY (`Product id`)
    REFERENCES `my_retail_oltp_db`.`Product` (`Product id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `my_retail_oltp_db`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_retail_oltp_db`.`Customer` (
  `Customer id` INT NOT NULL,
  `First Name` VARCHAR(45) NOT NULL,
  `Last Name` VARCHAR(45) NOT NULL,
  `Phone Number` VARCHAR(10) NOT NULL,
  `Address` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  UNIQUE INDEX `Employee id_UNIQUE` (`Customer id` ASC) VISIBLE,
  PRIMARY KEY (`Customer id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `my_retail_oltp_db`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_retail_oltp_db`.`Order` (
  `Order id` INT NOT NULL,
  `Product id` INT NULL,
  `Quantity` INT NULL,
  `Customer Review` INT NULL,
  `Employee id` INT NULL,
  `Time` DATETIME(0) NULL,
  `Customer id` INT NULL,
  `Transaction Info` VARCHAR(45) NULL,
  PRIMARY KEY (`Order id`),
  INDEX `fk_Order_Employee1_idx` (`Employee id` ASC) VISIBLE,
  INDEX `fk_Order_Product1_idx` (`Product id` ASC) VISIBLE,
  INDEX `fk_Order_Customer1_idx` (`Customer id` ASC) VISIBLE,
  CONSTRAINT `fk_Order_Employee1`
    FOREIGN KEY (`Employee id`)
    REFERENCES `my_retail_oltp_db`.`Employee` (`Employee id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_Product1`
    FOREIGN KEY (`Product id`)
    REFERENCES `my_retail_oltp_db`.`Product` (`Product id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_Customer1`
    FOREIGN KEY (`Customer id`)
    REFERENCES `my_retail_oltp_db`.`Customer` (`Customer id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;