-- MySQL Script generated by MySQL Workbench
-- Fri Oct 16 18:52:55 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `my_web_db` DEFAULT CHARACTER SET utf8 ;
USE `my_web_db` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_web_db`.`User` (
  `FirstName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `UserID` INT NOT NULL,
  `EmailAddress` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`UserID`),
  UNIQUE INDEX `UserID_UNIQUE` (`UserID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_web_db`.`Product` (
  `ProductName` VARCHAR(45),
  `ProductID` INT NOT NULL,
  PRIMARY KEY (`ProductID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Download`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_web_db`.`Download` (
  `Filename` VARCHAR(45) NOT NULL,
  `UserID` INT NOT NULL,
  `ProductID` INT NOT NULL,
  `Date/Time` DATETIME(0) NOT NULL,
  PRIMARY KEY (`Filename`),
  INDEX `fk_Download_Product_idx` (`ProductID` ASC) VISIBLE,
  INDEX `fk_Download_User1_idx` (`UserID` ASC) VISIBLE,
  CONSTRAINT `fk_Download_Product`
    FOREIGN KEY (`ProductID`)
    REFERENCES `my_web_db`.`Product` (`ProductID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Download_User1`
    FOREIGN KEY (`UserID`)
    REFERENCES `my_web_db`.`User` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


INSERT INTO product VALUES(
"xbox",
"1"
);

INSERT INTO product VALUES(
"gameboy",
"2"
);

INSERT INTO user VALUES(
"Bill",
"Paid",
"1",
"billpaid@game.com"
);

INSERT INTO user VALUES(
"No",
"Cash",
"2",
"nocash911@game.com"
);

INSERT INTO download VALUES(
"1dollargame",
"1",
"1",
NOW()
);

INSERT INTO download VALUES(
"100dollargame",
"1",
"2",
NOW()
);

INSERT INTO download VALUES(
"freegamefor200dollar",
"2",
"2",
NOW()
);

SELECT *
FROM download;

SELECT EmailAddress, FirstName, LastName, `Date/Time`, filename, ProductName
FROM download d
LEFT JOIN `user` u
ON u.UserID = d.UserID
LEFT JOIN product p
ON d.ProductID= p.ProductID
ORDER BY EmailAddress DESC, ProductName ASC;